Просмотр истории без ограничения по кол-ву и повторов
Stepan5024/java-kanban pull request #1
Opened 2024-03-13 20:08 UTC by Stepan5024

В классе InMemoryHistoryManager реализован список внутри которого сохраняются просмотры в формате связанного списка. Т.е. элементы выстраиваются в порядке их добавления в список. Удаление происходит по ключу Id внутри HashMap.

Вспомогательный класс Node нужен для навигации по предыдущим и последующим элементам списка.
Новые методы add linkLast remove removeNode - позволяют соблюдать порядок добавления. Также был убран лимит по кол-ву записей в истории.

В Main реализован новый сценарий показывающий работу данной функциональности.
![tg_image_861158760](https://github.com/Stepan5024/java-kanban/assets/29542338/9e77c136-2833-431f-8816-c608bf2e43bd)

2024-03-13 21:07 UTC, felixoff commented on test/controller/history/InMemoryHistoryManagerTest.java
> +                "Новая квартира по адресу Москва ул. Дружбы");
Одинаковые строки можно вынести в отдельную переменную для избежания дубляжей.

2024-03-14 06:19 UTC, breannly requested changes

2024-03-14 06:19 UTC, breannly commented on src/controller/history/HistoryManager.java
>      ArrayList<Task> getHistory();
лучше завязываться на интерфейсе, а не на реализации

List<Task> getHistory();

2024-03-14 06:19 UTC, breannly commented on src/controller/history/InMemoryHistoryManager.java
> +    public HashMap<Long, Node> getRecentTasks() {
лучше завязываться на интерфейсе, а не на реализации

Map<Long, Node> getRecentTask()

2024-03-14 06:19 UTC, breannly commented on src/controller/history/InMemoryHistoryManager.java
> +        ArrayList<Task> historyList = new ArrayList<>();
лучше завязываться на интерфейсе, а не на реализации

List<Task> historyList = new ArrayList<>();

2024-03-14 06:19 UTC, breannly commented on src/test/controller/history/InMemoryHistoryManagerTest.java
> +        /*Assertions.assertTrue(listOfReturnedHistory.size() <= COUNT_OF_RECENT_TASK,
в коде лучше не оставлять комменты

2024-03-14 17:19 UTC, Stepan5024 commented
Вынес текстовые метки в поля классов 
![image](https://github.com/Stepan5024/java-kanban/assets/29542338/725a0125-22e6-47ee-b153-2598e76515b7)
И инициализирую их в отдельном методе
![image](https://github.com/Stepan5024/java-kanban/assets/29542338/f91fba10-80ce-4d59-a59c-a2a642511068)


Также поправил завязку в объектах, чтобы ссылка была на интерфейс, а не на реализацию

![image](https://github.com/Stepan5024/java-kanban/assets/29542338/5d8e1d5f-c5c7-492c-aca1-b89fc9699f72)
![image](https://github.com/Stepan5024/java-kanban/assets/29542338/31cb936f-c91f-4d56-8f67-109b3a4debfa)

2024-03-15 07:36 UTC, merged